### ISSUE TITLE
Error when using a kubeconfig file that references external program

### ISSUE THREAD

**Issue by Emilio-Pega** [unbroken-dome/gradle-helm-plugin#74]
Gradle 6

If the plugin is configured to use a kubeconfig file that references an external program (like one used for AWS authentication), it fails, because the PATH environmental variable is not forwarded to the Worker API

Example kubeconfig using the external `aws-iam-authenticator` program to validate for AWS

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <some aws authority>
    server: <some aws server>
  name: <some aws name>
contexts:
- context:
    cluster: <some aws cluster>
    user: <some aws user>
  name: <some aws name>
current-context: <some aws context>
kind: Config
preferences: {}
users:
- name: <some aws user>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - platform-validation-pipeline-cluster-eks
      command: aws-iam-authenticator
      env: null
```

Error
```
Error: Kubernetes cluster unreachable: Get <aws cluser>: getting credentials: exec: exec: "aws-iam-authenticator": executable file not found in $PATH
```
