### ISSUE TITLE
plugin doesn't merge custom values with external chart

### ISSUE THREAD

**Issue by malov** [unbroken-dome/gradle-helm-plugin#76]
This plugin doesn't merge correctly external chart with custom override values.

This is Chart.yaml I have:
```
apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Airflow scheduler
name: msmt-airflow
version: 0.1.0
home: https://mylink
maintainers:
  - name: Me
    email: intelligenc@me.com
dependencies:
  - name: airflow
    version: "6.10.4"
    repository: "https://kubernetes-charts.storage.googleapis.com/"
```
This is "helm" section in my build.gradle
```
helm {
    def dbURL = "${dbType}://${dbUser}:${dbPassword}@${dbHost}:${dbPort}/${dbSchema}"
    namespace = 'ns'
    lint { strict = true }
    downloadClient {
        enabled.set(true)
        version.set("3.3.0")
    }
    filtering {
        values.put 'PG_URL',"${dbURL}"
        values.put 'TO_INIT', "false"
        values.put 'FERNET_KEY', "${fernetKey}"
    }
    charts {
        mychart {
            chartName = "${chart_name}"
            chartVersion ="${chart_version}"
            sourceDir = file("helm/${chart_name}")
        }
    }
    releases {
        def releaseName = "${deployEnv != 'prod' ? System.properties['user.name'] + '-' : ''}${project.name}-$deployEnv"
        "${releaseName}" { from charts."${chart_name}" }
    }
}
```
Result of running command `./gradlew :<myproject>:helmInstall` with this configuration is very different from running command `helm3 install mychart stable/airflow --version 6.10.4 --namespace <ns> --values myproject/helm/mychart/values.yaml` - custom values from `myproject/helm/mychart/values.yaml` are definitely not being applied.

I'm using plugin version 1.2.1 and Gradle version 6.6
